site_name: AINewsTracker
site_description: 'Leveraging AI to analyse financial news'
site_author: 'AlgoETS Team(Antoine Boucher, Mohamed Ilias, Makhlouf Hennine)'
site_url: 'https://algoets.github.io/AINewsTracker/'

repo_name: 'algoets/AINewsTracker'
repo_url: 'https://github.com/AlgoETS/AINewsTracker'

theme:
  name: material
  palette:
    primary: blue
    accent: light blue
  media: "(prefers-color-scheme)"
  toggle:
        icon: material/brightness-auto
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: 'img/favicon.ico'
  logo: 'img/AINewsTracker_transparent.svg'

plugins:
  - mkdocstrings
  - search:
      lang: en
  - build_plantuml:
      render: 'server'
      server: 'http://www.plantuml.com/plantuml'
      output_format: 'svg'
      diagram_root: 'docs/diagrams'
      output_folder: 'out'
      input_folder: 'src'
      theme_enabled: true


nav:
  - Home: index.md
  - About: about.md
  - Getting Started: getting-started.md
  - Overview: overview.md
  - API Reference: api.md
  - Diagram: diagrams.md
  - Reference: refences.md
  - Contacts: contact.md
